string="mi mama me mima"
contador = 0
print(string.center(40,"="))
contador = string.count("M")
print(f"\nLa letra M se encontro {contador} veces de la cadena: '{string}'")
contador = string.count("m")
print(f"\nLa letra m se encontro {contador} veces de la cadena: '{string}'")
contador = string.count("mama")
print(f"\nLa letra mama se encontro {contador} veces de la cadena: '{string}'")
contador = string.count("me mima")
print(f"\nLa letra me mima se encontro {contador} veces de la cadena: '{string}'")
contador = string.count("ma")
print(f"\nLa letra ma se encontro {contador} veces de la cadena: '{string}'")
contador = string.count("m",13)
print(f"\nLa letra m se encontro {contador} veces, desde la posicion 13 de la cadena: '{string}'")
contador = string.count("m",100)
print(f"\nLa letra m se encontro {contador} veces, desde la posicion 100 de la cadena: '{string}'")
contador = string.count("m",-3)
print(f"\nLa letra m se encontro {contador} veces, desde la posicion -3 de  la cadena: '{string}'")
contador = string.count("m",3,7)
print(f"\nLa letra m se encontro {contador} veces, desde la posicion 3 hasta la posicion  7 de la cadena: '{string}'")
contador = string.count("m",100,100)
print(f"\nLa letra m se encontro {contador} veces, desde la posicion 100 hasta la posicion 100 de la cadena: '{string}'")
contador = string.count("m",-4,-1)
print(f"\nLa letra m se encontro {contador} veces, desde la posicion -4 hasta la posicion -1 de la cadena: '{string}'")
