print("Accediendo a las posiciones de una lista".center(60,"*"))
print()

marcas = ["Apple","Samsung","Xiaomi","Huawei"]
print(f"\nLista completa: {marcas}")
print(f"\nElementos que componen la lista: - len(marcas): {len(marcas)} y posiciones: {len(marcas)-1}")
print(f"\nmarcas[1]: {marcas[1]}")
print(f"\nmarcas[3]: {marcas[3]}")
print(f"\nmarcas[-1]: {marcas[-1]}")
print(f"\nmarcas[-3]: {marcas[-3]}")
print(f"\nmarcas[1:3]: {marcas[1:3]}")
print(f"\nmarcas[:2]: {marcas[:2]}")
print(f"\nmarcas[1:3]: {marcas[1:3]}")
print(f"\nmarcas[:]: {marcas[:]}")
print(f"\nmarcas[-1]: {marcas[-1]}")
print()
print(marcas)
print(f"\nGenerando error marcas[4]: {marcas[4]}")
