print("Agregando un  elemento a la lista")
print()
letras = ["a","b","c","d"]
print(f"letras: {letras}")
letras.append("e")
print(f"letras: {letras}")
print()
print("Agregando tres elemento a la lista")
print()
letras = ["a","b","c","d"]
print(f"letras: {letras}")
letras.append("e")
letras.append("f")
letras.append("g")
print(f"letras: {letras}")
print()
print("Agregando tres elemento  de distinto tipo de datos")
print()
letras = ["a","b","c","d"]
print(f"letras: {letras}")
letras.append(5)
letras.append(1.5)
letras.append(True)
print(f"letras: {letras}")
print()
